{% set data = load_setup_py_data() %}

package:
  name: franklin
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/franklin.git

build:
  number: 0
  script: python -m pip install . -vv
  # entry_points:
  #   - franklin = franklin:franklin

requirements:
  host:
    - python
    - pip
  run:  # your library dependencies
    - python
    - requests>=2.32.3
    - colorama>=0.4.6
    - readchar>=4.0.5
    - click
    - psutil

channels:  # channels for your library dependencies
  - uibcdf
  - conda-forge
#  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build=24 # from 25 the output file is a .conda not .tar.bz2
  - conda-verify
  
test:
  imports:
    - franklin

about:
  home: https://github.com/munch-group/franklin.git
  license: MIT
  dev_url: https://github.com/munch-group/franklin.git
  doc_url: https://munch-group.org/franklin
