# {% set data = load_setup_py_data() %}

# package:
#   name: franklin
#   version: {{ data.get('version') }}  

{% set pyproject = load_file_data('pyproject.toml') %}
{% set package = pyproject.get('package', {}) %}

package:
  name: franklin
  version: {{ package.get('version') }}

source:
  git_url: https://github.com/munch-group/franklin.git

build:
  number: 0
  script: python -m pip install . -vv
  entry_points:
    - franklin = franklin:franklin

requirements:
  host:
    - python
    - pip
  run:  # your library dependencies
    - python
    - requests>=2.32.3
    - colorama>=0.4.6
    - readchar>=4.0.5
    - click
    - click-plugins
    - psutil
    - jupyter
    - packaging
    - yaml
    - pyperclip    
    - git
    - gitui
    # - wslu # [win]

channels:  # channels for your library dependencies
  - conda-forge

dependencies:   # keep this block with only these packages
  - anaconda-client
  - conda-build=24 # from 25 the output file is a .conda not .tar.bz2
  - conda-verify
  # - conda-forge/label/python_rc::_python_rc # Dummy package to force selection of python_rc channel when channel_priority is set to strict

test:
  imports:
    - franklin

about:
  home: https://github.com/munch-group/franklin.git
  license: MIT
  dev_url: https://github.com/munch-group/franklin.git
  doc_url: https://munch-group.org/franklin
