project:
  type: book
  output-dir: ../../_build/pages/students
  # post-render: 
  #   - quarto render --to html --profile ta  

book:
  title: "Franklin for students"
  # title: "<br>"
  subtitle: "The MBG jupyter exercise tool"
  # description: 'A course in bioinformatics and programming'
  # author: "Kasper Munch"
  sidebar:
    title: "Content"
    collapse-level: 1
    background: "white"      
  chapters:
    - index.qmd
    - part: "Jupyter"
      chapters:
      - ../jupyter.qmd
    - part: "Docker"
      chapters: 
      - ../jupyter.qmd
  downloads: [pdf]

#bibliography: references.bib

  
# embed-resources: true

format:
  html:
    mainfont: "Passata"
    theme: 
      - default
      - custom.scss
    highlight-style: kate 
    fig-width: 5
    fig-height: 3
    filters:
      - quarto
      - headers.lua
    notebook-links: global
    # number-sections: false
    number-sections: true      
    code-block-bg: "#f9f9f9"
    # code-tools: true    
  pdf:
    documentclass: scrbook
    papersize: a4
    highlight-style: kate 
    fig-width: 7
    fig-height: 5
    toc-depth: 2
    secPrefix:
      - "exercise"
      - "exercises"
    include-in-header:
      - file: header_extra.tex
  # epub:
  #   cover-image: cover.png
  #   highlight-style: kate 
  #   # epub-fonts: DejaVuSans-*.ttf