import click
from . import docker as _docker
from . import jupyter as _jupyter
from . import utils
import time
import sys
from .config import REQUIRED_GB_FREE_DISK

@click.group()
def franklin():
    """
    Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.

    \b
    Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 

    Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla.    
    """

franklin.add_command(_jupyter.jupyter)
franklin.add_command(_docker.docker)
# franklin.add_command(_devel.devel)
# franklin.add_command(_about.about)


about = f"""

"""+click.style("""Wikipedia entry on Franklin""", fg='green')+"""

Rosalind Elsie Franklin (25 July 1920 – 16 April 1958)[1] was a British chemist and X-ray crystallographer whose work was central to the understanding of the molecular structures of DNA (deoxyribonucleic acid), RNA (ribonucleic acid), viruses, coal, and graphite.[2] Although her works on coal and viruses were appreciated in her lifetime, Franklin's contributions to the discovery of the structure of DNA were largely unrecognised during her life, for which Franklin has been variously referred to as the "wronged heroine",[3] the "dark lady of DNA",[4] the "forgotten heroine",[5] a "feminist icon",[6] and the "Sylvia Plath of molecular biology".[7]

Franklin graduated in 1941 with a degree in natural sciences from Newnham College, Cambridge, and then enrolled for a PhD in physical chemistry under Ronald George Wreyford Norrish, the 1920 Chair of Physical Chemistry at the University of Cambridge. Disappointed by Norrish's lack of enthusiasm,[8] she took up a research position under the British Coal Utilisation Research Association (BCURA) in 1942. The research on coal helped Franklin earn a PhD from Cambridge in 1945.[9] Moving to Paris in 1947 as a chercheur (postdoctoral researcher) under Jacques Mering at the Laboratoire Central des Services Chimiques de l'État, she became an accomplished X-ray crystallographer. After joining King's College London in 1951 as a research associate, Franklin discovered some key properties of DNA, which eventually facilitated the correct description of the double helix structure of DNA.[3] Owing to disagreement with her director, John Randall, and her colleague Maurice Wilkins, Franklin was compelled to move to Birkbeck College in 1953.

Franklin is best known for her work on the X-ray diffraction images of DNA while at King's College London, particularly Photo 51, taken by her student Raymond Gosling, which led to the discovery of the DNA double helix for which Francis Crick, James Watson, and Maurice Wilkins shared the Nobel Prize in Physiology or Medicine in 1962.[10][11] While Gosling actually took the famous Photo 51, Maurice Wilkins showed it to James Watson without her permission.[12]

Watson suggested that Franklin would have ideally been awarded a Nobel Prize in Chemistry, along with Wilkins but it was not possible because the pre-1974 rule dictated that a Nobel prize could not be awarded posthumously unless the nomination had been made for a then-alive candidate before 1 February of the award year and Franklin died a few years before 1962 when the discovery of the structure of DNA was recognised by the Nobel committee.[13][14]

Working under John Desmond Bernal, Franklin led pioneering work at Birkbeck on the molecular structures of viruses.[15] On the day before she was to unveil the structure of tobacco mosaic virus at an international fair in Brussels, Franklin died of ovarian cancer at the age of 37 in 1958. Her team member Aaron Klug continued her research, winning the Nobel Prize in Chemistry in 1982.

"""+click.style("""Early life""", fg='green')+"""

Franklin was born in 50 Chepstow Villas,[16] Notting Hill, London, into an affluent and influential British Jewish family.[1][17][18]

"""+click.style("""Family""", fg='green')+"""

Franklin's father, Ellis Arthur Franklin (1894–1964), was a politically liberal London merchant banker who taught at the city's Working Men's College, and her mother was Muriel Frances Waley (1894–1976). Rosalind was the elder daughter and the second child in the family of five children. David (1919–1986) was the eldest brother while Colin (1923–2020), Roland (1926–2024), and Jenifer (born 1929) were her younger siblings.[19]

Franklin's paternal great-uncle was Herbert Samuel (later Viscount Samuel), who was the Home Secretary in 1916 and the first practising Jew to serve in the British Cabinet.[20] Her aunt, Helen Caroline Franklin, known in the family as Mamie, was married to Norman de Mattos Bentwich, who was the Attorney General in the British Mandate of Palestine.[21] Helen was active in trade union organisation and the women's suffrage movement and was later a member of the London County Council.[22][23] Franklin's uncle, Hugh Franklin, was another prominent figure in the suffrage movement, although his actions therein embarrassed the Franklin family. Rosalind's middle name, "Elsie", was in memory of Hugh's first wife, who died in the 1918 flu pandemic.[19] Her family was actively involved with the Working Men's College, where her father taught the subjects of electricity, magnetism, and the history of the Great War in the evenings, later becoming the vice principal.[24][25]

Franklin's parents helped settle Jewish refugees from Europe who had escaped the Nazis, particularly those from the Kindertransport.[26] They took in two Jewish children to their home, and one of them, a nine-year-old Austrian, Evi Eisenstädter, shared Jenifer's room.[27] (Evi's father Hans Mathias Eisenstädter had been imprisoned in Buchenwald, and after liberation, the family adopted the surname "Ellis".)[28][29]

"""+click.style("""Education""", fg='green')+"""

From early childhood, Franklin showed exceptional scholastic abilities. At age six, she joined her brother Roland at Norland Place School, a private day school in West London. At that time, her aunt Mamie (Helen Bentwich), described her to her husband: "Rosalind is alarmingly clever – she spends all her time doing arithmetic for pleasure, and invariably gets her sums right."[30] Franklin also developed an early interest in cricket and hockey. At age nine, she entered a boarding school, Lindores School for Young Ladies in Sussex.[31] The school was near the seaside, and the family wanted a good environment for Franklin's delicate health.[32]

Franklin was 11 when she went to St Paul's Girls' School in Hammersmith, west London, one of the few girls' schools in London that taught physics and chemistry.[31][33][34] At St Paul's, she excelled in science, Latin,[35] and sports.[36] Franklin also learned German, and became fluent in French, a language she would later find useful. Franklin topped her classes, and won annual awards. Her only educational weakness was in music, for which the school music director, the composer Gustav Holst, once called upon her mother to enquire whether she might have suffered from hearing problems or tonsillitis.[37] With six distinctions, Franklin passed her matriculation in 1938, winning a scholarship for university, the School Leaving Exhibition of £30 a year for three years, and £5 from her grandfather.[38] Franklin's father asked her to give the scholarship to a deserving refugee student.[31]


"""+click.style("""Cambridge and World War II""", fg='green')+"""

Franklin went to Newnham College, Cambridge, in 1938 and studied chemistry within the Natural Sciences Tripos. There, she met the spectroscopist Bill Price, who worked with her as a laboratory demonstrator and who later became one of her senior colleagues at King's College London.[39] In 1941 Franklin was awarded second-class honours from her final exams. The distinction was accepted as a bachelor's degree in qualifications for employment. Cambridge began awarding titular BA and MA degrees to women from 1947 and the previous women graduates retroactively received these earned degrees.[40] In her last year at Cambridge, Franklin met a French refugee Adrienne Weill, a former student of Marie Curie, who had a huge influence on her life and career and who helped her to improve her conversational French.[41][42]

Franklin was awarded a research fellowship at Newnham College, with which she joined the physical chemistry laboratory of the University of Cambridge to work under Ronald George Wreyford Norrish, who later won the Nobel Prize in Chemistry. In her one year of work there, Franklin did not have much success.[43] As described by his biographer, Norrish was "obstinate and almost perverse in argument, overbearing and sensitive to criticism".[44] He could not decide upon the assignment of work for her. At that time Norrish was succumbing due to heavy drinking. Franklin wrote that he made her despise him completely.[45]

Resigning from Norrish's Lab, Franklin fulfilled the requirements of the National Service Acts by working as an assistant research officer at the British Coal Utilisation Research Association (BCURA) in 1942.[15] The BCURA was located on the Coombe Springs Estate near Kingston upon Thames near the southwestern boundary of London. Norrish acted as advisor to the military at BCURA. John G. Bennett was the director. Marcello Pirani and Victor Goldschmidt, both refugees from the Nazis, were consultants and lectured at BCURA while Franklin worked there.[2]

During her BCURA research Franklin initially stayed at Adrienne Weill's boarding house in Cambridge until her cousin, Irene Franklin, proposed that they share living quarters at a vacated house in Putney that belonged to her uncle. With Irene, Rosalind volunteered as an Air Raid Warden and regularly made patrols to see the welfare of people during air raids.[46]

Franklin studied the porosity of coal using helium to determine its density.[47] Through this, she discovered the relationship between the fine constrictions in the pores of coals and the permeability of the porous space. By concluding that substances were expelled in order of molecular size as temperature increased, she helped classify coals and accurately predict their performance for fuel purposes and for production of wartime devices such as gas masks.[48] This work was the basis of Franklin's PhD thesis The physical chemistry of solid organic colloids with special reference to coal for which the University of Cambridge awarded her a PhD in 1945.[9] It was also the basis of several papers.[2]

"""+click.style("""Career and research""", fg='green')+"""

"""+click.style("""Paris""", fg='green')+"""

With World War II ending in 1945, Franklin asked Adrienne Weill for help and to let her know of job openings for "a physical chemist who knows very little physical chemistry, but quite a lot about the holes in coal." At a conference in the autumn of 1946, Weill introduced Franklin to Marcel Mathieu, a director of the Centre national de la recherche scientifique (CNRS), the network of institutes that comprises the major part of the scientific research laboratories supported by the French government. This led to her appointment with Jacques Mering at the Laboratoire Central des Services Chimiques de l'État in Paris. Franklin joined the labo (as referred to by the staff) of Mering on 14 February 1947 as one of the fifteen chercheurs (researchers).[49][50]

Mering was an X-ray crystallographer who applied X-ray diffraction to the study of rayon and other amorphous substances, in contrast to the thousands of regular crystals that had been studied by this method for many years.[2] He taught her the practical aspects of applying X-ray crystallography to amorphous substances. This presented new challenges in the conduct of experiments and the interpretation of results. Franklin applied them to further problems related to coal and to other carbonaceous materials, in particular the changes to the arrangement of atoms when these are converted to graphite.[2] She published several further papers on this work which has become part of the mainstream of the physics and chemistry of coal and carbon. Franklin coined the terms graphitising and non-graphitising carbon. The coal work was covered in a 1993 monograph,[51] and in the regularly-published textbook Chemistry and Physics of Carbon.[52] Mering continued the study of carbon in various forms, using X-ray diffraction and other methods.[53]

In 1950 Franklin was granted a three-year Turner & Newall Fellowship to work at King's College London. In January 1951 she started working as a research associate in the Medical Research Council's (MRC) Biophysics Unit, directed by John Randall.[54] She was originally appointed to work on X-ray diffraction of proteins and lipids in solution, but Randall redirected Franklin's work to DNA fibres[55] because of new developments in the field, and she was to be the only experienced experimental diffraction researcher at King's at the time.[56][57] Randall made this reassignment, even before Franklin started working at King's, because of the pioneering work by DNA researcher Maurice Wilkins, and he reassigned Raymond Gosling, the graduate student who had been working with Wilkins, to be her assistant.[58]

In 1950 Swiss chemist Rudolf Signer in Berne prepared a highly purified DNA sample from calf thymus. He freely distributed the DNA sample, later referred to as the Signer DNA, in early May 1950 at the meeting of the Faraday Society in London, and Wilkins was one of the recipients.[59] Even using crude equipment, Wilkins and Gosling had obtained a good-quality diffraction picture of the DNA sample which sparked further interest in this molecule.[60] But Randall had not indicated to them that he had asked Franklin to take over both the DNA diffraction work and guidance of Gosling's thesis.[61] It was while Wilkins was away on holiday that Randall, in a letter in December 1950, assured Franklin that "as far as the experimental X-ray effort there would be for the moment only yourself and Gosling."[62] Randall's lack of communication about this reassignment significantly contributed to the well documented friction that developed between Wilkins and Franklin.[63] When Wilkins returned, he handed over the Signer DNA and Gosling to Franklin.[62]

Franklin, now working with Gosling,[64] started to apply her expertise in X-ray diffraction techniques to the structure of DNA. She used a new fine-focus X-ray tube and microcamera ordered by Wilkins, but which she refined, adjusted and focused carefully. Drawing upon her physical chemistry background, a critical innovation Franklin applied was making the camera chamber that could be controlled for its humidity using different saturated salt solutions.[62] When Wilkins enquired about this improved technique, she replied in terms which offended him as she had "an air of cool superiority".[65]

Franklin's habit of intensely looking people in the eye while being concise, impatient and direct unnerved many of her colleagues. In stark contrast, Wilkins was very shy, and slowly calculating in speech while he avoided looking anyone directly in the eye.[66] With the ingenious humidity-controlling camera, Franklin was soon able to produce X-ray images of better quality than those of Wilkins. She immediately discovered that the DNA sample could exist in two forms: at a relative humidity higher than 75%, the DNA fibre became long and thin; when it was drier, it became short and fat. She originally referred to the former as "wet" and the latter as "crystalline."[62]

On the structure of the crystalline DNA, Franklin first recorded the analysis in her notebook, which reads: "Evidence for spiral [meaning helical] structure. Straight chain untwisted is highly improbable. Absence of reflections on meridian in χtalline [crystalline] form suggests spiral structure."[62] An immediate discovery from this was that the phosphate group lies outside of the main DNA chain; Franklin, however could not make out whether there could be two or three chains.[67] She presented their data at a lecture in November 1951, in King's College London. In her lecture notes, Franklin wrote the following:

The results suggest a helical structure (which must be very closely packed) containing 2, 3 or 4 co-axial nucleic acid chains per helical unit, and having the phosphate groups near the outside.[68]

Franklin then named "A" and "B" respectively for the "crystalline" and "wet" forms. (The biological functions of A-DNA were discovered only 60 years later.[69]) Because of the intense personality conflict developing between Franklin and Wilkins, Randall divided the work on DNA. Franklin chose the data rich "A" form while Wilkins selected the "B" form.[70][71]


"""+click.style("""A satirical death note of A-DNA helix by Franklin and Gosling.""", fg='green')+"""


By the end of 1951 it became generally accepted at King's that the B-DNA was a helix, but after Franklin had recorded an asymmetrical image in May 1952, Franklin became unconvinced that the A-DNA was a helix.[72] In July 1952, as a practical joke on Wilkins (who frequently expressed his view that both forms of DNA were helical), Franklin and Gosling produced a funeral notice regretting the 'death' of helical A-DNA, which runs:

It is with great regret that we have to announce the death, on Friday 18th July 1952 of DNA helix (crystalline). Death followed a protracted illness which an intensive course of Besselised [referring to Bessel function that was used to analyse the X-ray diffraction patterns[73]] injections had failed to relieve. A memorial service will be held next Monday or Tuesday. It is hoped that Dr M H F Wilkins will speak in memory of the late helix. [Signed Rosalind Franklin and Raymond Gosling.][74]

During 1952 they worked at applying the Patterson function to the X-ray pictures of DNA they had produced. This was a long and labour-intensive approach but would yield significant insight into the structure of the molecule.[75] Franklin was fully committed to experimental data and was sternly against theoretical or model buildings, as she said, "We are not going to speculate, we are going to wait, we are going to let the spots on this photograph tell us what the [DNA] structure is."[74] The X-ray diffraction pictures, including the landmark Photo 51 taken by Gosling at this time,[60] have been called by John Desmond Bernal as "amongst the most beautiful X-ray photographs of any substance ever taken".[76]

By January 1953 Franklin had reconciled her conflicting data, concluding that both DNA forms had two helices, and had started to write a series of three draft manuscripts, two of which included a double helical DNA backbone (see below). Franklin's two A-DNA manuscripts reached Acta Crystallographica in Copenhagen on 6 March 1953, the day before Crick and Watson had completed their model on B-DNA. Franklin must have mailed them while the Cambridge team was building their model, and certainly had written them before she knew of their work.[77] On 8 July 1953 Franklin modified one of these "in proof" Acta articles, "in light of recent work" by the King's and Cambridge research teams.[78]

The third draft paper was on the B-DNA, dated 17 March 1953, which was discovered years later amongst her papers, by Franklin's Birkbeck colleague, Aaron Klug.[79] He then published in 1974 an evaluation of the draft's close correlation with the third of the original trio of 25 April 1953 Nature DNA articles.[75] Klug designed this paper to complement the first article he had written in 1968 defending Franklin's significant contribution to DNA structure. Klug had written this first article in response to the incomplete picture of Franklin's work depicted in James Watson's 1968 memoir, The Double Helix.[67]

As vividly described by Watson, he travelled to King's on 30 January 1953 carrying a preprint of Linus Pauling's incorrect proposal for DNA structure. Since Wilkins was not in his office, Watson went to Franklin's lab with his urgent message that they should all collaborate before Pauling discovered his error. The unimpressed Franklin became angry when Watson suggested she did not know how to interpret her own data. Watson hastily retreated, backing into Wilkins who had been attracted by the commotion. Wilkins commiserated with his harried friend and then showed Watson Franklin's DNA X-ray image.[80] Watson, in turn, showed Wilkins a prepublication manuscript by Pauling and Robert Corey, which contained a DNA structure remarkably like their first incorrect model.[81]


"""+click.style("""Discovery of DNA structure""", fg='green')+"""


In November 1951 James Watson and Francis Crick of the Cavendish Laboratory in Cambridge University had started to build a molecular model of the B-DNA using data similar to that available to both teams at King's. Based on Franklin's lecture in November 1951 that DNA was helical with either two or three stands, they constructed a triple helix model, which was immediately proven to be flawed.[62] In particular, the model had the phosphate backbone of the molecules forming a central core. But Franklin pointed out that the progressive solubility of DNA crystals in water meant that the strongly hydrophilic phosphate groups were likely to be on the outside of the structure; while the experimental failure to titrate the CO- and NH2 groups of the bases meant that these were more likely to be inaccessible in the interior of the structure. This initial setback led Watson and Crick to focus on other topics for most of the next year.

Model building had been applied successfully in the elucidation of the structure of the alpha helix by Linus Pauling in 1951,[71][82] but Franklin was opposed to prematurely building theoretical models, until sufficient data were obtained to properly guide the model building. She took the view that building a model was to be undertaken only after enough of the structure was known.[72][83] Franklin's conviction was only reinforced when Pauling and Corey also came up in the late 1952 (published in February 1953[84]) with an erroneous triple helix model.[74] Ever cautious, Franklin wanted to eliminate misleading possibilities. Photographs of her Birkbeck work table show that Franklin routinely used small molecular models, although certainly not ones on the grand scale successfully used at Cambridge for DNA.

The arrival in Cambridge of Linus Pauling's flawed paper in January 1953 prompted the head of the Cavendish Laboratory, Lawrence Bragg, to encourage Watson and Crick to resume their own model building.[85] Six weeks of intense efforts followed, as they tried to guess how the nucleotide bases pack into the core of the DNA structure, within the broad parameters set by the experimental data from the team at King's, that the structure should contain one or more helices with a repeat distance of 34 Angstroms, with probably ten elements in each repeat; and that the hydrophilic phosphate groups should be on the outside (though as Watson and Crick struggled to come up with a structure they at times departed from each of these assumptions during the process).[85]

Crick and Watson received a further impetus in the middle of February 1953 when Crick's thesis advisor, Max Perutz, gave Crick a copy of a report written for a Medical Research Council biophysics committee visit to King's in December 1952, containing many of Franklin's crystallographic calculations.[86] This decisively confirmed the 34 Angstrom repeat distance; and established that the structure had C2 symmetry, immediately confirming to Crick that it must contain an equal number of parallel and anti-parallel strands running in opposite directions.[85]

Since Franklin had decided to transfer to Birkbeck College and Randall had insisted that all DNA work must stay at King's, Wilkins was given copies of Franklin's diffraction photographs by Gosling. By 28 February 1953 Watson and Crick felt they had solved the problem enough for Crick to proclaim (in the local pub) that they had "found the secret of life".[87] However, they knew they must complete their model before they could be certain.[88] The closeness of fit to the experimental data from King's was an essential corroboration of the structure.[85][89]

Watson and Crick finished building their model on 7 March 1953, a day before they received a letter from Wilkins stating that Franklin was finally leaving and they could put "all hands to the pump".[90] This was also one day after Franklin's two A-DNA papers had reached Acta Crystallographica. Wilkins came to see the model the following week, according to Franklin's biographer Brenda Maddox, on 12 March, and allegedly informed Gosling on his return to King's.[91]

One of the most critical and overlooked moments in DNA research was how and when Franklin realised and conceded that B-DNA was a double helical molecule. When Klug first examined Franklin's documents after her death, he initially came to an impression that Franklin was not convinced of the double helical nature until the knowledge of the Cambridge model.[67] But Klug later discovered the original draft of the manuscript (dated 17 March 1953) from which it became clear that Franklin had already resolved the correct structure. The news of Watson–Crick model reached King's the next day, 18 March,[75] suggesting that Franklin would have learned of it much later since she had moved to Birkbeck. Further scrutiny of her notebook revealed that Franklin had already thought of the helical structure for B-DNA in February 1953 but was not sure of the number of strands, as she wrote: "Evidence for 2-chain (or 1-chain helix)."[92] Her conclusion on the helical nature was evident, though she failed to understand the complete organisation of the DNA strands, as the possibility of two strands running in opposite directions did not occur to her.[75]

Towards the end of February Franklin began to work out the indications of double strands, as she noted: "Structure B does not fit single helical theory, even for low layer-lines." It soon dawned to her that the B-DNA and A-DNA were structurally similar,[92] and perceived A-DNA as an "unwound version" of B-DNA.[75] Franklin and Gosling wrote a five-paged manuscript on 17 March titled "A Note on Molecular Configuration of Sodium Thymonucleate."[93] After the Watson–Crick model was known, there appeared to be only one (hand-written) modification after the typeset at the end of the text which states that their data was consistent with the model,[75] and appeared as such in the trio of 25 April 1953 Nature articles; the other modification being a deletion of "A Note on" from the title.[94][95]

As Franklin considered the double helix, she also realised that the structure would not depend on the detailed order of the bases, and noted that "an infinite variety of nucleotide sequences would be possible to explain the biological specificity of DNA".[85] However she did not yet see the complementarity of the base-pairing – Crick and Watson's breakthrough of 28 February, with all its biological significance; nor indeed at this point did she yet have the correct structures of the bases, so even if she had tried, she would not have been able to make a satisfactory structure.[85] Science historians Nathaniel C. Comfort, of Johns Hopkins University, and Matthew Cobb, of the University of Manchester, explained that "She did not have time to make these final leaps, because Watson and Crick beat her to the answer."[85]

Weeks later, on 10 April, Franklin wrote to Crick for permission to see their model.[96] Franklin retained her scepticism for premature model building even after seeing the Watson–Crick model, and remained unimpressed. She is reported to have commented, "It's very pretty, but how are they going to prove it?" As an experimental scientist, Franklin seems to have been interested in producing far greater evidence before publishing-as-proven a proposed model. Accordingly, her response to the Watson–Crick model was in keeping with her cautious approach to science.[97]

Crick and Watson published their model in Nature on 25 April 1953, in an article describing the double-helical structure of DNA with only a footnote acknowledging "having been stimulated by a general knowledge of Franklin and Wilkins' 'unpublished' contribution."[98] Actually, although it was the bare minimum, they had just enough specific knowledge of Franklin and Gosling's data upon which to base their model. As a result of a deal struck by the two laboratory directors, articles by Wilkins and Franklin, which included their X-ray diffraction data, were modified and then published second and third in the same issue of Nature, seemingly only in support of the Crick and Watson theoretical paper which proposed a model for the B-DNA.[99][95] Most of the scientific community hesitated several years before accepting the double helix proposal. At first mainly geneticists embraced the model because of its obvious genetic implications.[100][101][102]


"""+click.style("""""", fg='green')+"""Birkbeck College


Franklin left King's College London in mid-March 1953 for Birkbeck College, in a move that had been planned for some time and that she described (in a letter to Adrienne Weill in Paris) as "moving from a palace to the slums ... but pleasanter all the same".[103] She was recruited by physics department chair John Desmond Bernal,[104] a crystallographer who was a communist, known for promoting female crystallographers. Her new laboratories were housed in 21 Torrington Square, one of a pair of dilapidated and cramped Georgian houses containing several different departments; Franklin frequently took Bernal to task over the careless attitudes of some of the other laboratory staff, notably after workers in the pharmacy department flooded her first-floor laboratory with water on one occasion.[105]

Despite the parting words of Bernal to stop her interest in nucleic acids, Franklin helped Gosling to finish his thesis, although she was no longer his official supervisor. Together, they published the first evidence of double helix in the A form of DNA in the 25 July issue of Nature.[106] At the end of 1954, Bernal secured funding for Franklin from the Agricultural Research Council (ARC), which enabled her to work as a senior scientist supervising her own research group.[107][108] John Finch, a physics student from King's College London, subsequently joined Franklin's group, followed by Kenneth Holmes, a Cambridge graduate, in July 1955. Despite the ARC funding, Franklin wrote to Bernal that the existing facilities remained highly unsuited for conducting research "...my desk and lab are on the fourth floor, my X-ray tube in the basement, and I am responsible for the work of four people distributed over the basement, first and second floors on two different staircases."[108]


"""+click.style("""RNA research""", fg='green')+"""


Franklin continued to explore another major nucleic acid, RNA, a molecule equally central to life as DNA. She again used X-ray crystallography to study the structure of the tobacco mosaic virus (TMV), an RNA virus. Her meeting with Aaron Klug in early 1954 led to a longstanding and successful collaboration. Klug had just then earned his PhD from Trinity College, Cambridge, and joined Birkbeck in late 1953. In 1955, Franklin published her first major works on TMV in Nature, where she described that all TMV virus particles were of the same length.[109] This was in direct contradiction to the ideas of the eminent virologist Norman Pirie, though Franklin's observation ultimately proved correct.[110]

Franklin assigned the study of the complete structure of TMV to her PhD student Holmes. They soon discovered (published in 1956) that the covering of TMV was protein molecules arranged in helices.[111] Her colleague Klug worked on spherical viruses with his student Finch, with Franklin coordinating and overseeing the work.[112] As a team, from 1956 they started publishing seminal works on TMV,[113] cucumber virus 4 and turnip yellow mosaic virus.[114]

Franklin also had a research assistant, James Watt, subsidised by the National Coal Board and was now the leader of the ARC group at Birkbeck.[115] The Birkbeck team members continued working on RNA viruses affecting several plants, including potato, turnip, tomato and pea.[116] In 1955 the team was joined by an American post-doctoral student Donald Caspar. He worked on the precise location of RNA molecules in TMV. In 1956, Caspar and Franklin published individual but complementary papers in the 10 March issue of Nature, in which they showed that the RNA in TMV is wound along the inner surface of the hollow virus.[117][118] Caspar was not an enthusiastic writer, and Franklin had to write the entire manuscript for him.[119]

Franklin's research grant from ARC expired at the end of 1957, and she was never given the full salary proposed by Birkbeck.[63] After Bernal requested ARC chairman Lord Rothschild, she was given a one-year extension ending in March 1958.[120]

Expo 58, the first major international fair after World War II, was to be held in Brussels in 1958.[121][122] Franklin was invited to make a five-foot high model of TMV, which she started in 1957. Her materials included table tennis balls and plastic bicycle handlebar grips.[123] The Brussels world's fair, with an exhibit of her virus model at the International Science Pavilion, opened on 17 April, one day after she died.[124]


"""+click.style("""Polio virus""", fg='green')+"""


In 1956 Franklin visited the University of California, Berkeley, where colleagues suggested her group research the polio virus.[125] In 1957 she applied for a grant from the United States Public Health Service of the National Institutes of Health, which approved £10,000 (equivalent to £304,532 in 2023[126]) for three years, the largest fund ever received at Birkbeck.[127][128] In her grant application, Franklin mentioned her new interest in animal virus research. She obtained Bernal's consent in July 1957, though serious concerns were raised after Franklin disclosed her intentions to research live, instead of killed, polio virus at Birkbeck. Eventually, Bernal arranged for the virus to be safely stored at the London School of Hygiene and Tropical Medicine during the group's research. With her group, Franklin then commenced deciphering the structure of the polio virus while it was in a crystalline state. She attempted to mount the virus crystals in capillary tubes for X-ray studies, but was forced to end her work due to her rapidly failing health.[129]

After Franklin's death Klug succeeded her as group leader, and he, Finch and Holmes continued researching the structure of the polio virus. They eventually succeeded in obtaining extremely detailed X-ray images of the virus. In June 1959 Klug and Finch published the group's findings, revealing the polio virus to have icosahedral symmetry, and in the same paper suggested the possibility for all spherical viruses to possess the same symmetry, as it permitted the greatest possible number (60) of identical structural units.[130] The team moved to the Laboratory of Molecular Biology, Cambridge, in 1962[131] and the old Torrington Square laboratories were demolished four years later, in May 1966.[132]


"""+click.style("""Personal life""", fg='green')+"""


Franklin was best described as an agnostic. Her lack of religious faith apparently did not stem from anyone's influence, rather from her own line of thinking. She developed her scepticism as a young child. Her mother recalled that she refused to believe in the existence of God, and remarked, "Well, anyhow, how do you know He isn't She?"[133] She later made her position clear, now based on her scientific experience, and wrote to her father in 1940:

[S]cience and everyday life cannot and should not be separated. Science, for me, gives a partial explanation of life ... I do not accept your definition of faith i.e. belief in life after death ... Your faith rests on the future of yourself and others as individuals, mine in the future and fate of our successors. It seems to me that yours is the more selfish ...[134] [as to] the question of a creator. A creator of what? ... I see no reason to believe that a creator of protoplasm or primeval matter, if such there be, has any reason to be interested in our insignificant race in a tiny corner of the universe.[135]

However, Franklin did not abandon Jewish traditions. As the only Jewish student at Lindores School, she had Hebrew lessons on her own while her friends went to church.[136] She joined the Jewish Society while in her first term at Cambridge, out of respect of her grandfather's request.[137] Franklin confided to her sister that she was "always consciously a Jew".[135]

Franklin loved travelling abroad, particularly trekking. She first "qualified" at Christmas 1929 for a vacation at Menton, France, where her grandfather went to escape the English winter.[138] Her family frequently spent vacations in Wales or Cornwall. A trip to France in 1938 gave Franklin a lasting love for France and its language. She considered the French lifestyle at that time as "vastly superior to that of English".[139] In contrast, Franklin described English people as having "vacant stupid faces and childlike complacency".[140] Her family was almost stuck in Norway in 1939, as World War II was declared on their way home.[141] In another instance, Franklin trekked the French Alps with Jean Kerslake in 1946, which almost cost her her life. Franklin slipped off a slope, and was barely rescued.[142] But she wrote to her mother, "I am quite sure I could wander happily in France forever. I love the people, the country and the food."[143] Of note are also Franklin's visits to Yugoslavia. She collaborated with Slovenian chemist Dušan Hadži [sl] whom she met at King's College in 1951. In the 1950s, she visited Slovenia one or more times where she held a lecture on coal in Ljubljana and visited the Julian Alps (Triglav and Bled). Her best-known trekking photograph was presumably created by Hadži in May 1952 and depicts Franklin against the background of the natural rock formation of Heathen Maiden. She also collaborated with the Croatian physicist Katarina Kranjc. She held lectures in Zagreb and Belgrade and visited Dalmatia.[144]

Franklin made several professional trips to the United States, and was particularly jovial among her American friends and constantly displayed her sense of humour. William Ginoza of the University of California, Los Angeles, later recalled that Franklin was the opposite of Watson's description of her, and as Maddox comments, Americans enjoyed her "sunny side".[145]

In his book The Double Helix, Watson provides his first-person account of the search for and discovery of DNA. He paints a sympathetic but sometimes critical portrait of Franklin. He praises her intellect and scientific acumen, but portrays Franklin as difficult to work with and careless with her appearance. After introducing her in the book as "Rosalind", he writes that he and his male colleagues usually referred to her as "Rosy", the name people at King's College London used behind her back.[146] Franklin did not want to be called by that name because she had a great-aunt Rosy. In the family, she was called "Ros".[147] To others, Franklin was simply "Rosalind". She made it clear to an American visiting friend, Dorothea Raacke, while sitting with her at Crick's table in The Eagle pub in Cambridge: Raacke asked her how she would like to be addressed, she replied "I'm afraid it will have to be Rosalind", adding "Most definitely not Rosy."[148]

Franklin often expressed her political views. She initially blamed Winston Churchill for inciting the war, but later admired him for his speeches. Franklin actively supported Professor John Ryle as an independent candidate for parliament in the 1940 Cambridge University by-election, but he was unsuccessful.[149]

Franklin did not seem to have an intimate relationship with anyone, and always kept her deepest personal feelings to herself. After her younger days, she avoided close friendship with the opposite sex. In her later years, Evi Ellis, who had shared her bedroom when a child refugee and who was then married to Ernst Wohlgemuth[29] and had moved to Notting Hill from Chicago, tried matchmaking her with Ralph Miliband but failed. Franklin once told Evi that a man who had a flat on the same floor as hers asked if she would like to come in for a drink, but she did not understand the intention.[150] She was quite infatuated by her French mentor Mering, who had a wife and a mistress.[143] Mering also admitted that he was captivated by her "intelligence and beauty".[151] According to Anne Sayre, Franklin did confess her feeling for Mering when she was undergoing a second surgery, but Maddox reported that the family denied this.[152] Mering wept when he visited her later,[153] and destroyed all her letters after her death.[154]

Franklin's closest personal affair was probably with her once post-doctoral student Donald Caspar. In 1956, she visited him at his home in Colorado after her tour to University of California, Berkeley, and she was known to remark later that Caspar was one "she might have loved, might have married". In her letter to Sayre, Franklin described him as "an ideal match".[155]

Illness, death, and burial


In mid-1956, while on a work-related trip to the United States, Franklin first began to suspect a health problem. While in New York, she found difficulty in zipping her skirt; her stomach had bulged. Back in London, Franklin consulted Mair Livingstone,[156] who asked her, "You're not pregnant?" to which she retorted, "I wish I were." Her case was marked "URGENT".[157] An operation on 4 September of the same year revealed two tumours in her abdomen.[158] After this period and other periods of hospitalisation, Franklin spent time convalescing with various friends and family members. These included Anne Sayre, Francis Crick, his wife Odile, with whom Franklin had formed a strong friendship,[148] and finally with the Roland and Nina Franklin family where Rosalind's nieces and nephews bolstered her spirits.

Franklin chose not to stay with her parents because her mother's uncontrollable grief and crying upset her too much. Even while undergoing cancer treatment, Franklin continued to work, and her group continued to produce results – seven papers in 1956 and six more in 1957.[159] At the end of 1957 Franklin again fell ill and she was admitted to the Royal Marsden Hospital. On 2 December she made her will. Franklin named her three brothers as executors and made her colleague Aaron Klug the principal beneficiary, who would receive £3,000 and her Austin car. Of her other friends, Mair Livingstone would get £2,000, Anne Piper £1,000, and her nurse Miss Griffith £250. The remainder of the estate was to be used for charities.[160]

Franklin returned to work in January 1958 and was also given a promotion to Research Associate in Biophysics on 25 February.[161] She fell ill again on 30 March and died a few weeks later on 16 April 1958 in Chelsea, London,[162][163] of bronchopneumonia, secondary carcinomatosis, and ovarian cancer. Exposure to X-ray radiation is sometimes considered to be a possible factor in Franklin's illness.[164] Other members of her family have died of cancer, and the incidence of gynaecological cancer is known to be disproportionately high among Ashkenazi Jews.[165] Franklin's death certificate states: A Research Scientist, Spinster, Daughter of Ellis Arthur Franklin, a Banker.[166] She was interred on 17 April 1958 in the family plot at Willesden United Synagogue Cemetery at Beaconsfield Road in London Borough of Brent. The inscription on her tombstone reads:[167][168]

Franklin's will was proven on 30 June with her estate assessed for probate at £11,278 10s. 9d. (equivalent to £332,828 in 2023[126]).[169]


"""+click.style("""Controversies after death""", fg='green')+"""


"""+click.style("""Alleged sexism toward Franklin""", fg='green')+"""


Anne Sayre, Franklin's friend and one of her biographers, says in her 1975 book, Rosalind Franklin and DNA: "In 1951 ... King's College London as an institution, was not distinguished for the welcome that it offered to women ... Rosalind ... was unused to purdah [a religious and social institution of female seclusion] ... there was one other female on the laboratory staff".[170] The molecular biologist Andrzej Stasiak notes: "Sayre's book became widely cited in feminist circles for exposing rampant sexism in science."[171] Farooq Hussain says: "there were seven women in the biophysics department ... Jean Hanson became an FRS, Dame Honor B. Fell, Director of Strangeways Laboratory, supervised the biologists".[172] Maddox, Franklin's biographer, states: "Randall ... did have many women on his staff ... they found him ... sympathetic and helpful."[173]

Sayre asserts that "while the male staff at King's lunched in a large, comfortable, rather clubby dining room" the female staff of all ranks "lunched in the student's hall or away from the premises".[174][175] However, Elkin claims that most of the MRC group (including Franklin) typically ate lunch together in the mixed dining room discussed below.[66] And Maddox says, of Randall: "He liked to see his flock, men and women, come together for morning coffee, and at lunch in the joint dining room, where he ate with them nearly every day."[173] Francis Crick also commented that "her colleagues treated men and women scientists alike".[176]

Sayre also discusses at length Franklin's struggle in pursuing science, particularly her father's concern about women in academic professions.[177] This account had led to accusations of sexism in regard to Ellis Franklin's attitude to his daughter. A good deal of information explicitly claims that he strongly opposed her entering Newnham College.[178][179][180][181] The Public Broadcasting Service (PBS) biography of Franklin goes further, stating that he refused to pay her fees, and that an aunt stepped in to do that for her.[182] Her sister, Jenifer Glynn, has stated that those stories are myths, and that her parents fully supported Franklin's entire career.[5]

Sexism is said to pervade the memoir of one peer, James Watson, in his book The Double Helix, published 10 years after Franklin's death and after Watson had returned from Cambridge to Harvard.[183] His Cambridge colleague, Peter Pauling, wrote in a letter, "Morris [sic] Wilkins is supposed to be doing this work; Miss Franklin is evidently a fool."[184] Crick acknowledges later, "I'm afraid we always used to adopt – let's say, a patronizing attitude towards her."[185]

Glynn accuses Sayre of erroneously making her sister a feminist heroine,[186] and sees Watson's The Double Helix as the root of what she calls the "Rosalind Industry". She conjectures that the stories of alleged sexism would "have embarrassed her [Rosalind Franklin] almost as much as Watson's account would have upset her",[5] and declared that "she [Rosalind] was never a feminist."[187] Klug and Crick have also concurred that Franklin was definitely not a feminist.[188]

Franklin's letter to her parents in January 1939 is often taken as reflecting her own prejudiced attitude, and the claim that she was "not immune to the sexism rampant in these circles". In the letter, she remarked that one lecturer was "very good, though female".[189] Maddox maintains that was a circumstantial comment rather than an example of gender bias, and that it was a expression of admiration because, at the time, woman teachers of science were a rarity. In fact, Maddox says, Franklin laughed at men who were embarrassed by the appointment of the first female professor, Dorothy Garrod.[190]


"""+click.style("""Contribution to the model/structure of DNA""", fg='green')+"""


Franklin's first important contributions to the model popularised by Crick and Watson was her lecture at the seminar in November 1951, where she presented to those present, among them Watson, the two forms of the molecule, type A and type B, her position being that the phosphate units are located in the external part of the molecule. She also specified the amount of water to be found in the molecule in accordance with other parts of it, data that have considerable importance for the stability of the molecule. Franklin was the first to discover and articulate these facts, which constituted the basis for all later attempts to build a model of the molecule. However, Watson, at the time ignorant of the chemistry, failed to comprehend the crucial information, and this led to the construction of an incorrect three-helical model.[62]

The other contribution included a photograph of an X-ray diffaction pattern of B-DNA (called Photo 51),[191] taken by Franklin's student Gosling, that was briefly shown to Watson by Wilkins in January 1953,[192][193] and a report written for an MRC biophysics committee visit to King's in December 1952 which was shown by Perutz at the Cavendish Laboratory to both Crick and Watson. This MRC report contained data from the King's group, including some of Franklin's and Gosling's work, and was given to Crick – who was working on his thesis on haemoglobin structure – by his thesis supervisor Perutz, a member of the visiting committee.[194][195]

Sayre's biography of Franklin contains a story[196] alleging that the photograph 51 in question was shown to Watson by Wilkins without Franklin's permission,[171][197][198][199] and that this constituted a case of bad science ethics.[200] Others dispute this story, asserting that Wilkins had been given photograph 51 by Franklin's Ph.D. student Gosling because she was leaving King's to work at Birkbeck. There was allegedly nothing untoward in this transfer of data to Wilkins[192][201] because Director Randall had insisted that all DNA work belonged exclusively to King's. He had therefore instructed Franklin, in a letter, to even stop working on it and submit her data.[202] It was also implied, by Horace Freeland Judson, that Maurice Wilkins had taken the photograph out of Franklin's drawer, but this is also said to be incorrect.[203]

Likewise, Perutz saw "no harm" in showing an MRC report containing the conclusions of Franklin and Gosling's X-ray data analysis to Crick, since it had not been marked as confidential, although "The report was not expected to reach outside eyes".[204] Indeed, after the publication of Watson's The Double Helix exposed Perutz's act, he received so many letters questioning his judgment that he felt the need to both answer them all[205] and to post a general statement in Science excusing himself on the basis of being "inexperienced and casual in administrative matters".[206]

Perutz also claimed that the MRC information was already made available to the Cambridge team when Watson had attended Franklin's seminar in November 1951. A preliminary version of much of the important material contained in the 1952 December MRC report had been presented by Franklin in a talk she had given in November 1951, which Watson had attended but not understood.[77][207]

The Perutz letter was, as said, one of three, published with others by Wilkins and Watson, which discussed their various contributions. Watson clarified the importance of the data obtained from the MRC report as he had not recorded these data while attending Franklin's lecture in 1951. The upshot of all this was that, when Crick and Watson started to build their model, in February 1953, they were working with critical parameters that had been determined by Franklin in 1951, which she and Gosling had significantly refined in 1952, as well as with published data and other very similar data to those available at King's. It was generally believed that Franklin was never aware that her work had been used during construction of the model,[208] but Gosling, when asked in his 2013 interview if he believed she learned of this before her death, asserted "Yes. Oh, she did know about that."[209]

In 2023 an unpublished article for Time magazine in 1953 revealed two documents that showed a close collaboration of Franklin with Watson and Crick.[210][211] Reporting in Nature, Comfort and Cobb suggested new evidence in an opinion piece that Franklin was a contributor and "equal player" in process leading to the discovery of the molecular structure of DNA, rather than otherwise,[212][213] concluding that "the discovery of the structure of DNA was not seen [in 1953] as a race won by Watson and Crick, but as the outcome of a joint effort."[214] One manuscript written by Joan Bruce, a London journalist for Time, was never published and stored among Franklin's papers. It was prepared in consultation with Franklin,[215] who saw that Bruce's scientific presentation was not good enough for an article. Bruce clearly mentioned that "they [Franklin and Wilkins with Watson and Crick] linked up, confirming each other's work from time to time, or wrestling over a common problem," and that Franklin was often "checking the Cavendish model against her own X-rays, not always confirming the Cavendish structural theory."[214] Another document, a letter of Pauline Cowan from King's College inviting Crick to attend Franklin's lecture in January 1953, indicated that Crick was already familiar with the DNA data available at the time.[216] In an interview in Science News, Comfort and Cobb agreed that there were never stealing of any data, as the two teams shared their research information willingly.[217]


"""+click.style("""Recognition of her contribution to the model of DNA""", fg='green')+"""


Upon the completion of their model, Crick and Watson had invited Wilkins to be a co-author of their paper describing the structure.[218] Wilkins turned down this offer, as he had taken no part in building the model.[219] He later expressed regret that greater discussion of co-authorship had not taken place as this might have helped to clarify the contribution the work at King's had made to the discovery.[220] There is no doubt that Franklin's experimental data were used by Crick and Watson to build their model of DNA in 1953. Some, including Maddox, have explained this citation omission by suggesting that it may be a question of circumstance, because it would have been very difficult to cite the unpublished work from the MRC report they had seen.[91]

Indeed, a clear timely acknowledgment would have been awkward, given the unorthodox manner in which data were transferred from King's to Cambridge. However, methods were available. Watson and Crick could have cited the MRC report as a personal communication or else cited the Acta articles in press, or most easily, the third Nature paper that they knew was in press. One of the most important accomplishments of Maddox's widely acclaimed biography is that Maddox made a well-received case for inadequate acknowledgement. "Such acknowledgement as they gave her was very muted and always coupled with the name of Wilkins".[221]

Fifteen years after the fact the first clear recitation of Franklin's contribution appeared as it permeated Watson's account, The Double Helix, although it was buried under descriptions of Watson's (often quite negative) regard towards Franklin during the period of their work on DNA. This attitude is epitomized in the confrontation between Watson and Franklin over a preprint of Pauling's mistaken DNA manuscript.[222] Watson's words impelled Sayre to write her rebuttal, in which the entire chapter nine, "Winner Take All", has the structure of a legal brief dissecting and analyzing the topic of acknowledgement.[223]

Sayre's early analysis was often ignored because of perceived feminist overtones in her book. Watson and Crick did not cite the X-ray diffraction work of Wilkins and Franklin in their original paper, though they admit having "been stimulated by a knowledge of the general nature of the unpublished experimental results and ideas of Dr. M. H. F. Wilkins, Dr. R. E. Franklin and their co-workers at King's College London".[98] In fact, Watson and Crick cited no experimental data at all in support of their model. Franklin and Gosling's publication of the DNA X-ray image, in the same issue of Nature, served as the principal evidence:

Thus our general ideas are not inconsistent with the model proposed by Watson and Crick in the preceding communication.[95]


"""+click.style("""Nobel Prize""", fg='green')+"""


Franklin was never nominated for a Nobel Prize.[224][225] Her work was a crucial part in the discovery of DNA's structure, which, along with subsequent related work, led to Francis Crick, James Watson, and Maurice Wilkins being awarded a Nobel Prize in 1962.[226] Franklin had died in 1958, and during her lifetime, the DNA structure was not considered to be fully proven. It took Wilkins and his colleagues about seven years to collect enough data to prove and refine the proposed DNA structure. Moreover, its biological significance, as proposed by Watson and Crick, was not established. General acceptance for the DNA double helix and its function did not start until late in the 1950s, leading to Nobel nominations in 1960, 1961, and 1962 for Nobel Prize in Physiology or Medicine, and in 1962 for Nobel Prize in Chemistry.[227] The first breakthrough was from Matthew Meselson and Franklin Stahl in 1958, who experimentally showed the DNA replication of a bacterium, Escherichia coli.[228] In what is now known as the Meselson–Stahl experiment, DNA was found to replicate into two double-stranded helices, with each helix having one of the original DNA strands. This DNA replication was firmly established by 1961 after further demonstration in other species,[229] and of the stepwise chemical reaction.[230][231] According to the 1961 Crick–Monod letter, this experimental proof, along with Wilkins having initiated the DNA diffraction work, were the reasons why Crick felt that Wilkins should be included in the DNA Nobel Prize.[89]

In 1962 the Nobel Prize was subsequently awarded to Crick, Watson, and Wilkins.[15][232][233] Nobel rules now prohibit posthumous nominations (though this statute was not formally in effect until 1974) or splitting of Prizes more than three ways.[234][235] The award was for their body of work on nucleic acids and not exclusively for the discovery of the structure of DNA.[236] By the time of the award Wilkins had been working on the structure of DNA for more than 10 years, and had done much to confirm the Watson–Crick model.[237] Crick had been working on the genetic code at Cambridge and Watson had worked on RNA for some years.[238] Watson has suggested that ideally Wilkins and Franklin would have been awarded the Nobel Prize in Chemistry.[13] Pauling, who received the Nobel Peace Prize that year, believed and earlier warned the Nobel Committee in 1960 that "it might well be premature to make an award of a Prize to Watson and Crick, because of existing uncertainty about the detailed structure of nucleic acid. I myself feel that it is likely that the general nature of the Watson-Crick structure is correct, but that there is doubt about details."[239] He was partly right as an alternative of Watson-Crick base pairing, called the Hoogsteen base pairing that can form triple DNA strand, was discovered by Karst Hoogsteen in 1963.[240][241]

Aaron Klug, Franklin's colleague and principal beneficiary in her will, was the sole winner of the Nobel Prize in Chemistry 1982, "for his development of crystallographic electron microscopy and his structural elucidation of biologically important nucleic acid-protein complexes".[242] This work was exactly what Franklin had started and which she introduced to Klug, and it is highly plausible that, were she alive, Franklin would have shared the Nobel Prize.[243]

"""

@franklin.command()
def rosalind():
    click.echo_via_pager(utils.wrap(about))
