project:
  type: website
  output-dir: _build
  # resources:
    # - objects.txt
    # - objects-test.txt
  post-render: 
    # - quarto render --profile slides
    - quarto render pages/student/

execute:
  freeze: auto
  echo: true

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/docs/
    matplotlib:
      url: https://matplotlib.org/stable/
    scipy:
      url: https://docs.scipy.org/doc/scipy/
    statsmodels:
      url: https://www.statsmodels.org/stable/      
    # quartodoc-test:
    #   url: https://machow.github.io/quartodoc
    #   inv: objects-test.txt

website:
  title: "franklin"
  page-navigation: true
  navbar:
    left:
      # - file: examples/
      #   text: Examples
      - href: api/
        text: API reference
      - href: pages/student/
        text: Student site
    right:
      - icon: github
        href: https://github.com/munch-group/franklin/
  sidebar:
    - id: pages
      title: Get Started
      style: floating
      align: left
      contents:
        - pages/getting_started.qmd       
        - section: "Student"
          contents:
            - pages/student/index.qmd
        - section: "Educator"
          contents:
            - pages/create_edit.qmd
        - section: "Tutorials"
          contents:
            - pages/tutorials/terminal.qmd
            - pages/tutorials/jupyterlab.ipynb
            - pages/tutorials/developing_exercises.qmd
            - pages/tutorials/data_analysis.ipynb
            - pages/tutorials/plotting.ipynb
        - section: "About"
          contents:
            - pages/about/ssh.qmd
            - pages/about/git.qmd
            - pages/about/gitlab.qmd
            - pages/about/docker.qmd
        - section: "Infrastructure"
          contents:
            - pages/admin/overview.qmd
            - pages/admin/gitlab.qmd
            - pages/admin/docker.qmd
        # - section: "Source code"
        #   contents:
        #     - pages/admin/source.qmd
        #     - ../src/franklin/docker.py

comments:
  hypothesis: true

lightbox: true

format:
  html:
    # mainfont: "Passata"
    theme: 
      - cosmo
      # - custom.scss

  # theme:
  #   light: [cosmo]  # or flatly, darkly, etc.
  #   dark: [darkly]
  #   # Customize Bootstrap variables
  #   custom:
  #     navbar-bg: "#004080"     # background color
  #     navbar-fg: "#ffffff"     # foreground (text) color
  #     navbar-hover-color: "#cccccc"  # hover text color
                
    # theme: cosmo
    css:
      - api/_styles-quartodoc.css
      - styles.css
    toc: true
    sidebar:
      collapse-level: 1
      search: true  
    mermaid:
      theme: neutral     

quartodoc:
  style: pkgdown
  dir: api
  package: franklin
  render_interlinks: true
  options:
    signature_name: full
  renderer:
    style: markdown
    table_style: description-list
  sidebar: "api/_sidebar.yml"
  css: "api/_styles-quartodoc.css"

  sections:
    - title: Jupyter
      package: franklin.jupyter
      desc: |
        Some description...
      contents:
        - _run
    - title: Docker
      package: franklin.docker
      desc: |
        Some description...
      contents:
        - run
        - pull
          

    # - title: Some other section
    #   package: franklin.docker
    #   desc: |
    #     Some description...
    #   contents:
    #     - scriptname

