on:
  push:
    branches:
      - main

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - run: pip install jupyter #pandas pyyaml tabulate pycryptodome>3.10 pbkdf2 cryptography 

      # - uses: r-lib/actions/setup-r@v2
      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: |
      #       any::downloadthis
      #     # extra-packages: |
      #     #   any::downloadthis

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      - name: Render Quarto Project - default profile
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: default
        with:
          path: docs
          to: html

      # - name: Render Quarto Project - draft profile
      #   uses: quarto-dev/quarto-actions/render@v2
      #   env:
      #     QUARTO_PROFILE: slides
      #   with:
      #     path: .
      #     to: html


      - name: Install the dependencies
        working-directory: ./jupyterlite
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        working-directory: ./jupyterlite
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist --lite-dir jupyterlite
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../_build/dist



      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

    permissions:
      contents: write        
#     pages: write
